services:
  web:
    build: .
    container_name: fulldjango_app

    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - "8000:8000"

    volumes:
      - .:/pro

    env_file:
      - .env

    depends_on:
      - redis

  worker:
    build: .

    container_name: celery_worker

    command: celery -A pro worker -l info

    volumes:
      - .:/pro

    env_file:
      - .env

    depends_on:
      - redis

  redis:
    image: redis:8
    container_name: redis_cachenew

    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest

    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/pro/staticfiles
      - ./media:/pro/media

    depends_on:
      - web

    restart: always