# Generated by Django 5.2.16 on 2026-07-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.FileField(default=2, upload_to='students/'),
            preserve_default=False,
        ),
    ]
